// Comprehensive Driver Dataset for AgriConnect Fleet Console

export const DRIVER_PROFILE = {
  id: 1,
  driver_code: 'DRV-MH-8841',
  name: 'Rajesh Vitthal Patil',
  name_mr: 'राजेश विठ्ठल पाटील',
  phone: '+91 98221 44021',
  alt_phone: '+91 94220 88192',
  email: 'rajesh.patil.logistics@gmail.com',
  rating_avg: 4.92,
  total_trips: 84,
  on_time_rate: '99.4%',
  cargo_safety_rate: '100%',
  total_distance_km: 14820,
  years_experience: 9,
  home_apmc: 'Lasalgaon APMC Mandi Yard',
  district: 'Nashik',
  state: 'Maharashtra',
  aadhaar_status: 'Aadhaar e-KYC Verified',
  license_no: 'MH15 20180049210',
  license_type: 'Commercial HGMV / Transporter',
  license_valid_until: '18-Nov-2032',
  vahan_status: 'Verified Commercial Vahan',
  bank_name: 'State Bank of India',
  bank_branch: 'Niphad Main Branch',
  bank_account: 'SBI Direct DBT A/C *******4402',
  ifsc_code: 'SBIN0001429',
  upi_id: 'rajesh.patil@oksbi'
};

export const VEHICLE_DETAILS = {
  reg_no: 'MH 15 EG 4402',
  make_model: 'Eicher Pro 2049 (6-Wheel Cargo Truck)',
  category: 'Commercial Goods Carrier (LCV / High-Deck)',
  fuel_type: 'BS-VI Diesel (AdBlue SCR Compliant)',
  unladen_weight_kg: 2450,
  gross_vehicle_weight_kg: 6950,
  max_payload_tonnes: 4.5,
  max_payload_qtl: 45,
  deck_dimensions: '14.2 ft (L) × 6.2 ft (W) × 7.0 ft (H)',
  deck_type: 'Ventilated Wooden Slats with Anti-Bruise Rubber Liners',
  tarp_type: 'Heavy 550 GSM Aerated Water-Proof Tarpaulin with High-Tension Rachets',
  gps_device_id: 'APMC-GPS-MH15-8841',
  fastag_tag_id: 'NETC-FASTAG-MH15-8841-SBI',
  fastag_balance: 1850.00,
  fuel_level_pct: 78,
  tire_pressure_psi: 110,
  last_service_date: '28-Aug-2026',
  next_service_km: '18,500 km',
  odometer_km: 16420
};

export const COMPLIANCE_DOCUMENTS = [
  {
    id: 'fitness',
    title: 'RTO Commercial Fitness Certificate',
    doc_no: 'FC-MH15-2024-8841',
    authority: 'RTO Nashik (MH-15)',
    issued_date: '16-Aug-2024',
    valid_until: '15-Aug-2027',
    status: 'ACTIVE',
    badge: 'Valid (3 Years)',
    color: '#16a34a'
  },
  {
    id: 'insurance',
    title: 'Commercial Goods Transit & Third Party Insurance',
    doc_no: 'ICICI-LOMB-COMM-9941029',
    authority: 'ICICI Lombard General Insurance',
    issued_date: '01-Sep-2025',
    valid_until: '31-Aug-2027',
    status: 'ACTIVE',
    badge: 'Full Comprehensive',
    color: '#16a34a'
  },
  {
    id: 'puc',
    title: 'BS-VI Commercial Emission Certificate (PUC)',
    doc_no: 'PUC-MH15-2026-4402',
    authority: 'Govt. Approved Pollution Center #44',
    issued_date: '10-Jul-2026',
    valid_until: '09-Jan-2027',
    status: 'ACTIVE',
    badge: 'Green Pass (BS-VI)',
    color: '#16a34a'
  },
  {
    id: 'permit',
    title: 'Maharashtra All-District Goods Carriage Permit',
    doc_no: 'ST-PERMIT-MH-2024-1184',
    authority: 'Transport Commissioner, Maharashtra',
    issued_date: '12-Jan-2024',
    valid_until: '11-Jan-2029',
    status: 'ACTIVE',
    badge: 'All 36 Districts',
    color: '#16a34a'
  }
];

export const MOCK_AVAILABLE_LOADS = [
  {
    id: 'LOAD-2026-0906-A',
    job_code: 'JOB-2026-0906-901',
    commodity: 'Grade-A Red Onion (लाल कांदा)',
    variety: 'Nashik Gavran (गावराण)',
    quantity_qtl: 150,
    weight_tonnes: 15.0,
    distance_km: 14,
    est_transit_time: '25 mins',
    pickup_location: 'Farm Gate: Gut No. 84, Pimpalgaon Baswant',
    pickup_coords: '20.1742, 73.9821',
    farmer_name: 'Santosh Bhaurao Shinde',
    farmer_phone: '+91 98224 81920',
    drop_location: 'Lasalgaon APMC Logistics Bay 4',
    buyer_name: 'AgroFresh Supply Chain Ltd',
    freight_fee: 9200,
    toll_allowance: 0,
    escrow_status: '100% Locked in State Escrow',
    escrow_ref: '#SBI-MH-ESC-901-PREFUND',
    loading_time: 'Ready for Immediate Dispatch',
    urgency: 'HIGH',
    is_pooled: false,
    special_notes: 'Aerated tarpaulin mandatory; fragile cured onion skins. Zero transit moisture.'
  },
  {
    id: 'LOAD-2026-0906-B',
    job_code: 'JOB-2026-0906-904',
    commodity: 'Yellow Soyabean (सोयाबीन - JS-335)',
    variety: 'JS-335 Certified Seed Lot',
    quantity_qtl: 110,
    weight_tonnes: 11.0,
    distance_km: 26,
    est_transit_time: '45 mins',
    pickup_location: 'Farm Gate: Gut No. 112, Dindori Rural Shivar',
    pickup_coords: '20.2104, 73.8420',
    farmer_name: 'Kisan Baburao Jadhav',
    farmer_phone: '+91 94222 71092',
    drop_location: 'MahaOilseed Agro Industries, Ambad MIDC, Nashik',
    buyer_name: 'MahaOilseed Aggregators',
    freight_fee: 8650,
    toll_allowance: 80,
    escrow_status: '100% Locked in State Escrow',
    escrow_ref: '#SBI-MH-ESC-904-PREFUND',
    loading_time: 'Today by 4:00 PM',
    urgency: 'MEDIUM',
    is_pooled: false,
    special_notes: 'Moisture dry cargo; waterproof canopy required.'
  },
  {
    id: 'LOAD-2026-0906-C',
    job_code: 'JOB-POOL-2026-041',
    commodity: 'Consolidated Tomato Crates (टोमॅटो - 3 Farms)',
    variety: 'Abhinav Hybrid Red Tomato',
    quantity_qtl: 160,
    weight_tonnes: 16.0,
    distance_km: 38,
    est_transit_time: '1h 10m',
    pickup_location: '3 Cluster Points: Sinnar, Musalgaon, Pangri',
    pickup_coords: '19.8512, 73.9921',
    farmer_name: 'Sinnar Progressive FPO Cooperative',
    farmer_phone: '+91 98220 11993',
    drop_location: 'Vashi APMC Perishable Terminal, Navi Mumbai',
    buyer_name: 'Reliance Retail Fresh Hub',
    freight_fee: 17400,
    toll_allowance: 420,
    escrow_status: '100% Locked in State Escrow',
    escrow_ref: '#SBI-MH-ESC-POOL-041',
    loading_time: 'Night Transit (Dispatch 8:00 PM)',
    urgency: 'SCHEDULED',
    is_pooled: true,
    pooled_farmers: 3,
    special_notes: 'Plastic crates with corner-angle rubber strapping. Cold airflow run.'
  },
  {
    id: 'LOAD-2026-0906-D',
    job_code: 'JOB-2026-0906-912',
    commodity: 'Bhagwa Pomegranates (डाळिंब - Export Grade)',
    variety: 'Bhagwa Super Red (350g+)',
    quantity_qtl: 85,
    weight_tonnes: 8.5,
    distance_km: 74,
    est_transit_time: '1h 50m',
    pickup_location: 'Sangola Orchard Gate, Solapur Highway',
    pickup_coords: '17.4321, 75.1982',
    farmer_name: 'Ganesh Pandurang Deshmukh',
    farmer_phone: '+91 94231 66201',
    drop_location: 'APMC Vashi Cold Packhouse, Navi Mumbai',
    buyer_name: 'Gulf Fresh Fruits Exports Ltd',
    freight_fee: 18900,
    toll_allowance: 320,
    escrow_status: '100% Locked in State Escrow',
    escrow_ref: '#SBI-MH-ESC-912-PREFUND',
    loading_time: 'Tomorrow Early Morning 5:00 AM',
    urgency: 'SCHEDULED',
    is_pooled: false,
    special_notes: 'Air-conditioned insulated thermal blanket needed. Zero hard braking.'
  }
];

export const COMPLETED_TRIPS_HISTORY = [
  {
    id: 'TRIP-8840',
    trip_code: 'JOB-2026-0904-8840',
    deal_ref: 'AC-TXN-8840',
    date: '04-Sep-2026',
    completed_at: '04-Sep-2026, 4:30 PM',
    commodity: '150 Qtl Export Grade Onion',
    crop_name: 'Nashik Red Onion',
    origin: 'Dindori Farm Gate, Gut 52',
    destination: 'AgroFresh Receiving Hub, Lasalgaon Bay 4',
    consignor: 'Santosh Bhaurao Shinde',
    consignee: 'AgroFresh Supply Chain Ltd',
    distance_km: 32,
    tare_weight_kg: 2450,
    gross_weight_kg: 17450,
    net_produce_kg: 15000,
    freight_amount: 8450.00,
    toll_charges: 0.00,
    demurrage_fee: 0.00,
    net_payout: 8450.00,
    payout_status: 'SETTLED_TO_DBT',
    bank_utr: 'SBI991204910482',
    driver_rating: 5.0,
    eway_bill_no: 'EWB-2710-9941-8840',
    gate_pass_no: 'APMC-GP-2026-8840',
    proof_photo_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'TRIP-8792',
    trip_code: 'JOB-2026-0901-8792',
    deal_ref: 'AC-TXN-8792',
    date: '01-Sep-2026',
    completed_at: '01-Sep-2026, 8:15 PM',
    commodity: '4.2 MT Thompson Seedless Grapes',
    crop_name: 'Export Table Grapes',
    origin: 'Mohadi Packhouse, Dindori',
    destination: 'JNPT Cold Port Terminal, Navi Mumbai',
    consignor: 'Sahyadri Farmers Producer Co.',
    consignee: 'EuroAgri Logistics Cold Dock 3',
    distance_km: 198,
    tare_weight_kg: 2450,
    gross_weight_kg: 6650,
    net_produce_kg: 4200,
    freight_amount: 19800.00,
    toll_charges: 480.00,
    demurrage_fee: 0.00,
    net_payout: 20280.00,
    payout_status: 'SETTLED_TO_DBT',
    bank_utr: 'SBI990184910231',
    driver_rating: 5.0,
    eway_bill_no: 'EWB-2710-8812-8792',
    gate_pass_no: 'APMC-GP-2026-8792',
    proof_photo_url: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'TRIP-8740',
    trip_code: 'JOB-2026-0828-8740',
    deal_ref: 'AC-TXN-8740',
    date: '28-Aug-2026',
    completed_at: '28-Aug-2026, 6:45 AM',
    commodity: '180 Plastic Crates Ripe Tomatoes',
    crop_name: 'Fresh Salad Tomatoes',
    origin: 'Otur Farm Gate, Junnar',
    destination: 'Vashi APMC Perishable Terminal Dock',
    consignor: 'Kisan Baburao Jadhav',
    consignee: 'Mumbai Fresh Sourcing Cooperative',
    distance_km: 142,
    tare_weight_kg: 2450,
    gross_weight_kg: 7850,
    net_produce_kg: 5400,
    freight_amount: 14200.00,
    toll_charges: 340.00,
    demurrage_fee: 700.00,
    net_payout: 15240.00,
    payout_status: 'SETTLED_TO_DBT',
    bank_utr: 'SBI982847192801',
    driver_rating: 5.0,
    eway_bill_no: 'EWB-2710-7419-8740',
    gate_pass_no: 'APMC-GP-2026-8740',
    proof_photo_url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'TRIP-8690',
    trip_code: 'JOB-2026-0822-8690',
    deal_ref: 'AC-TXN-8690',
    date: '22-Aug-2026',
    completed_at: '22-Aug-2026, 3:10 PM',
    commodity: '140 Qtl Pooled Soybeans (3 Pickups)',
    crop_name: 'Soyabean (Yellow Seed)',
    origin: 'Sinnar Taluka (Musalgaon / Wavi)',
    destination: 'Jalna Agro Oilseed Processing Mill',
    consignor: 'Sinnar Progressive FPO',
    consignee: 'Jalna Extraction Plants Ltd',
    distance_km: 178,
    tare_weight_kg: 2450,
    gross_weight_kg: 16450,
    net_produce_kg: 14000,
    freight_amount: 16500.00,
    toll_charges: 280.00,
    demurrage_fee: 0.00,
    net_payout: 16780.00,
    payout_status: 'SETTLED_TO_DBT',
    bank_utr: 'SBI982204918234',
    driver_rating: 5.0,
    eway_bill_no: 'EWB-2710-6612-8690',
    gate_pass_no: 'APMC-GP-2026-8690',
    proof_photo_url: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&auto=format&fit=crop&q=80'
  },
  {
    id: 'TRIP-8610',
    trip_code: 'JOB-2026-0816-8610',
    deal_ref: 'AC-TXN-8610',
    date: '16-Aug-2026',
    completed_at: '16-Aug-2026, 1:40 PM',
    commodity: '3.5 MT Bhagwa Pomegranates',
    crop_name: 'Bhagwa Export Pomegranate',
    origin: 'Sangola Orchard, Solapur Highway',
    destination: 'Mumbai International Air Cargo Packhouse',
    consignor: 'Ganesh Pandurang Deshmukh',
    consignee: 'Global Cold Air Logistics',
    distance_km: 260,
    tare_weight_kg: 2450,
    gross_weight_kg: 5950,
    net_produce_kg: 3500,
    freight_amount: 22400.00,
    toll_charges: 510.00,
    demurrage_fee: 0.00,
    net_payout: 22910.00,
    payout_status: 'SETTLED_TO_DBT',
    bank_utr: 'SBI981604921948',
    driver_rating: 5.0,
    eway_bill_no: 'EWB-2710-5519-8610',
    gate_pass_no: 'APMC-GP-2026-8610',
    proof_photo_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80'
  }
];

export const TRANSPORT_REVIEWS = [
  {
    id: 1,
    reviewer: 'Santosh Bhaurao Shinde',
    role: 'Verified Farmer • Consignor',
    badgeType: 'farmer',
    location: 'Pimpalgaon Baswant, Nashik',
    commodity: '120 Qtl Grade-A Red Onion',
    route: 'Pimpalgaon Farm Gate ➔ Lasalgaon APMC Bay 4',
    tripCode: 'JOB-2026-0906-881',
    date: 'Today, 2:15 PM',
    stars: 5,
    tag: 'Aerated Tarping',
    comment: 'Rajesh arrived at our Pimpalgaon field at exactly 6:00 AM as scheduled. His Eicher truck was immaculate with clean, dry wooden deck slats and heavy-duty ventilated tarpaulins. Handled all 120 onion gunny bags with care — zero bag tearing and zero neck bruising. Shared his live GPS link throughout transit.'
  },
  {
    id: 2,
    reviewer: 'AgroFresh Supply Chain Ltd',
    role: 'Corporate APMC Buyer • Consignee',
    badgeType: 'buyer',
    location: 'Lasalgaon Cold Storage Bay 4',
    commodity: '150 Qtl Export Grade Onion',
    route: 'Dindori Farm ➔ AgroFresh Receiving Hub',
    tripCode: 'JOB-2026-0904-742',
    date: '2 days ago',
    stars: 5,
    tag: 'Quick Dock Clearance',
    comment: 'Superb transport discipline. Rajesh presented computer tare weight slips from certified APMC weighbridge with zero variance. Checked into our unloading dock within 10 minutes of arrival and uploaded geo-tagged unloading photos directly to the AgriConnect portal. We always prefer his vehicle for our procurement routes.'
  },
  {
    id: 3,
    reviewer: 'Sahyadri Farmers Producer Co.',
    role: 'FPO Logistics Lead',
    badgeType: 'fpo',
    location: 'Mohadi Cluster, Dindori',
    commodity: '4.2 MT Thompson Seedless Grapes',
    route: 'Mohadi Packhouse ➔ JNPT Cold Port, Navi Mumbai',
    tripCode: 'JOB-2026-0901-628',
    date: '5 days ago',
    stars: 5,
    tag: 'Delicate Perishables',
    comment: 'Transporting export-grade grapes requires extremely gentle driving over rural culverts. Rajesh drove at steady speeds, ensuring zero berry drop or vibration shock to our corrugated cartons. The temperature logs remained perfectly stable under his insulated thermal covers. 10/10 service.'
  },
  {
    id: 4,
    reviewer: 'Kisan Baburao Jadhav',
    role: 'Tomato Grower & Shipper',
    badgeType: 'farmer',
    location: 'Otur, Junnar / Narayangaon',
    commodity: '180 Plastic Crates Ripe Tomatoes',
    route: 'Otur Farm Gate ➔ Vashi APMC Terminal Dock',
    tripCode: 'JOB-2026-0828-519',
    date: '1 week ago',
    stars: 5,
    tag: 'Zero Transit Squashing',
    comment: 'Tomatoes are very delicate in hot afternoon runs. Rajesh used corner-angle straps with foam cushioning between crate stacks. Arrived at Vashi APMC at 3:30 AM ahead of the morning auction, giving us prime auction positioning and zero crushed crates. Genuine, polite and dependable driver.'
  },
  {
    id: 5,
    reviewer: 'Reliance Retail Agri Logistics Hub',
    role: 'Inward Quality Inspector',
    badgeType: 'buyer',
    location: 'Bhiwandi Distribution Center',
    commodity: '3.8 MT Mixed Exotic Vegetables',
    route: 'Nashik Greenhouses ➔ Bhiwandi Distribution Center',
    tripCode: 'JOB-2026-0824-482',
    date: '2 weeks ago',
    stars: 5,
    tag: '100% Inward Acceptance',
    comment: 'Clean vehicle fitness documentation, commercial Vahan registration verified, and driver carries all statutory BS-VI PUC and Goods Carrier insurance papers. Unloaded quickly at Dock 12. Transit time was well within the approved 4-hour corridor. Excellent professionalism.'
  },
  {
    id: 6,
    reviewer: 'Sinnar Progressive FPO Cooperative',
    role: 'Cluster Aggregator',
    badgeType: 'fpo',
    location: 'Sinnar Taluka',
    commodity: '140 Qtl Pooled Soybeans',
    route: '3 Sinnar Village Collection Points ➔ Jalna Oil Mill',
    tripCode: 'JOB-2026-0820-391',
    date: '2 weeks ago',
    stars: 5,
    tag: 'Multi-Stop Pooling',
    comment: 'Handled a tricky 3-point consolidated pickup across Musalgaon, Pangri, and Wavi villages without a single complaint. Accurately matched each farmer lot count against their digital gate pass and secured the entire load with heavy waterproof canopy. Delivered to Jalna with exact tare weight match.'
  },
  {
    id: 7,
    reviewer: 'Ganesh Pandurang Deshmukh',
    role: 'Pomegranate Grower',
    badgeType: 'farmer',
    location: 'Sangola, Solapur',
    commodity: '3.5 MT Bhagwa Pomegranates (Export Pack)',
    route: 'Sangola Orchard ➔ Mumbai Air Cargo Packhouse',
    tripCode: 'JOB-2026-0815-312',
    date: '3 weeks ago',
    stars: 5,
    tag: 'Export Handling',
    comment: 'Our Bhagwa pomegranate cartons were destined for Dubai export. Rajesh ensured the cargo was shaded from direct afternoon sun and drove smoothly without hard braking. The packhouse inspection team praised the zero-scuff delivery. His freight rate was totally transparent per APMC norms.'
  },
  {
    id: 8,
    reviewer: 'Shri Balaji Traders (Adat No. 44)',
    role: 'APMC Licensed Commission Agent',
    badgeType: 'buyer',
    location: 'Lasalgaon Mandi Yard',
    commodity: '110 Qtl Summer White Onion',
    route: 'Yeola Farm ➔ Lasalgaon Auction Yard',
    tripCode: 'JOB-2026-0810-277',
    date: '3 weeks ago',
    stars: 4,
    tag: 'Mandi Queue Discipline',
    comment: 'Very disciplined transporter who respects APMC mandi vehicle lane rules. Patiently waited in the designated unloading bay without causing traffic snarls. Uploaded gate slip promptly. Minor 15-minute wait during heavy market rush, but communication was clear throughout.'
  },
  {
    id: 9,
    reviewer: 'Vitthal Mahadevrao Kadam',
    role: 'Commercial Farmer',
    badgeType: 'farmer',
    location: 'Kopargaon, Ahilyanagar',
    commodity: '160 Bags Sharbati Wheat',
    route: 'Kopargaon ➔ Pune Hadapsar Flour Mill',
    tripCode: 'JOB-2026-0804-198',
    date: '1 month ago',
    stars: 5,
    tag: 'Moisture Protection',
    comment: 'It was pouring rain on our dispatch day. Rajesh had double layered tarpaulins with secure bottom tucks. Not a single drop of water touched our wheat bags. Weighbridge tare at Kopargaon and Pune matched within 5 kg (certified scale tolerance). Very trustworthy gentleman.'
  },
  {
    id: 10,
    reviewer: 'BigBasket Central Fresh Sourcing',
    role: 'Regional Logistics Coordinator',
    badgeType: 'buyer',
    location: 'Nashik Hub, Ambad MIDC',
    commodity: '4.0 MT Fresh Coriander & Leafy Greens',
    route: 'Trimbak Farms ➔ Ambad Cold Hub',
    tripCode: 'JOB-2026-0728-145',
    date: '1 month ago',
    stars: 5,
    tag: 'Cold Chain Speed',
    comment: 'Leafy vegetables have the highest respiration rate and perish within hours if delayed. Rajesh completed the Trimbak to Ambad run in just 48 minutes with open-air ventilation grilles active. Field heat was preserved at minimal levels. Seamless dual-escrow verification on the app.'
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 1,
    type: 'job',
    title: 'New High-Value Load Available',
    desc: '150 Qtl Onion load available near Pimpalgaon (7 km away) — ₹9,200 Pre-funded Escrow',
    time: '12 mins ago',
    unread: true,
    tabTarget: 'available_orders'
  },
  {
    id: 2,
    type: 'payment',
    title: 'Escrow Freight Payout Credited',
    desc: '₹8,450.00 credited to SBI A/c ending in 4402 for Job #JOB-2026-0904-8840 via State DBT Vault',
    time: '1 hour ago',
    unread: true,
    tabTarget: 'earnings'
  },
  {
    id: 3,
    type: 'status',
    title: 'Buyer Dock Inward Accepted',
    desc: 'AgroFresh receiving dock confirmed gross weight (17,450 kg) with zero variance. Digital slip generated.',
    time: '2 hours ago',
    unread: true,
    tabTarget: 'trip_history'
  },
  {
    id: 4,
    type: 'compliance',
    title: 'Commercial Fitness Certificate Valid',
    desc: 'Annual fitness inspection passed and logged with Maharashtra RTO — Valid till 15-Aug-2027',
    time: 'Yesterday',
    unread: false,
    tabTarget: 'vehicle_profile'
  },
  {
    id: 5,
    type: 'job',
    title: 'Consolidated Pooled Trip Available',
    desc: 'Pimpalgaon Cluster #04 formed: 3 Farm Pickups (160 Qtl total) — ₹17,400 Escrow Payout',
    time: '2 days ago',
    unread: false,
    tabTarget: 'available_orders'
  }
];

export const APMC_FAQS = [
  {
    id: 1,
    q: 'How does the APMC Dual-Escrow Freight Guarantee protect drivers?',
    a: 'Under Maharashtra APMC Act statutory rules, 100% of agreed freight charges are pre-funded into the State Escrow Vault by the buyer before the driver begins transit. Zero freight advance is needed. The moment the receiving dock uploads the inward weighment slip or 48 hours lapse, the funds are automatically wired directly to your verified SBI DBT bank account without any deductions.'
  },
  {
    id: 2,
    q: 'What should I do if the buyer delays unloading at the APMC dock?',
    a: 'Every APMC destination grants 2 hours of standard free unloading time from gate pass entry. If unloading is delayed past 2 hours, you are entitled by law to a statutory detention/demurrage fee of ₹350 per hour under Section 31-B. Simply submit a Demurrage Claim from the Support tab with your gate pass timestamp.'
  },
  {
    id: 3,
    q: 'What is the certified tolerance for weighbridge tare variance?',
    a: 'Standard legal metrology allows up to ±0.5% weight variance across calibrated electronic weighbridges due to road scale differences and natural transit respiration loss (moisture evaporation). Deductions for variance under 0.5% are prohibited by Mandi regulations.'
  },
  {
    id: 4,
    q: 'How are Highway Fastag toll charges reimbursed?',
    a: 'All state and national highway toll charges incurred along the designated transit route are automatically tracked via your NETC Fastag ID and added as an escrow surcharge paid by the buyer upon trip completion.'
  }
];
